import { execSync } from "node:child_process";

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const GITHUB_REPOSITORY = process.env.GITHUB_REPOSITORY;

if (!GITHUB_TOKEN || !GITHUB_REPOSITORY) {
  console.error("Missing GitHub environment variables");
  process.exit(1);
}


function getFileChurn(): [string, number][] {
  const output = execSync(
  "git log -n 100 --name-only --pretty=format:",
  { encoding: "utf8", maxBuffer: 1024 * 1024 * 10 } 
);


  const counts: Record<string, number> = {};

  for (const line of output.split("\n")) {
    if (!line) continue;
    if (line.startsWith(".github/")) continue;
    if (line.includes("package-lock")) continue;

    counts[line] = (counts[line] || 0) + 1;
  }

  return Object.entries(counts)
    .sort((a, b) => b[1] - a[1]);
}


async function createIssue(title: string, body: string) {
  const res = await fetch(
    `https://api.github.com/repos/${GITHUB_REPOSITORY}/issues`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${GITHUB_TOKEN}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title,
        body,
        labels: ["ai-suggested", "needs-review"],
      }),
    }
  );

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`Failed to create issue: ${text}`);
  }
}

async function main() {
  const churn = getFileChurn();

  if (churn.length === 0) {
    console.log("No churn detected");
    return;
  }

  const [file, count] = churn[0];

  if (count < 5) {
    console.log("Churn below threshold, skipping");
    return;
  }

  const title = `Investigate frequent changes in ${file}`;
  const body = `
This file was modified **${count} times in the last 30 days**.

Frequent churn often indicates:
- unstable behavior
- unclear responsibilities
- missing tests or abstractions

**Suggested next step**
Review whether this logic should be simplified, split, or better covered by tests.

_Automatically generated by repo tooling._
`;

  await createIssue(title, body);
  console.log("Issue created:", title);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
